package entity;
// Generated 11-ene-2019 12:11:12 by Hibernate Tools 4.3.1



/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int dni;
     private int modd;

    public MatriculaId() {
    }

    public MatriculaId(int dni, int modd) {
       this.dni = dni;
       this.modd = modd;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public int getModd() {
        return this.modd;
    }
    
    public void setModd(int modd) {
        this.modd = modd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getDni()==castOther.getDni())
 && (this.getModd()==castOther.getModd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDni();
         result = 37 * result + this.getModd();
         return result;
   }   


}


