package entity;
// Generated 11-ene-2019 12:11:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo  implements java.io.Serializable {


     private int modd;
     private Integer horas;
     private String descripcion;
     private String curso;
     private String nombre;
     private Set matriculas = new HashSet(0);

    public Modulo() {
    }

	
    public Modulo(int modd) {
        this.modd = modd;
    }
    public Modulo(int modd, Integer horas, String descripcion, String curso, String nombre, Set matriculas) {
       this.modd = modd;
       this.horas = horas;
       this.descripcion = descripcion;
       this.curso = curso;
       this.nombre = nombre;
       this.matriculas = matriculas;
    }
   
    public int getModd() {
        return this.modd;
    }
    
    public void setModd(int modd) {
        this.modd = modd;
    }
    public Integer getHoras() {
        return this.horas;
    }
    
    public void setHoras(Integer horas) {
        this.horas = horas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


