/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auto;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;

/**
 *
 * @author seran
 */
public class vDialogo extends javax.swing.JDialog {

    /**
     * Creates new form vDialogo
     */
    public vDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        bGroup.add(rbGasolina);
        rbGasolina.setSelected(true);
        bGroup.add(rbDiesel);
        bGroup.add(rbElectrico);
        bGroup.add(rbHibrido);
        ActionListener al = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (rbGasolina.isSelected() && cbTipoVehiculo.getSelectedIndex() == 0
                        || rbDiesel.isSelected() && cbTipoVehiculo.getSelectedIndex() == 1) {
                    cbTipoCambio.setEnabled(true);
                } else {
                    cbTipoCambio.setEnabled(false);
                }
            }
        };
        rbGasolina.addActionListener(al);
        rbDiesel.addActionListener(al);
        rbHibrido.addActionListener(al);
        rbElectrico.addActionListener(al);
        cbTipoVehiculo.addActionListener(al);

        tfPVP.addFocusListener(new FocusListener() {
            @Override
            public void focusLost(FocusEvent arg0) {
                try {
                    int pvp = Integer.parseInt(tfPVP.getText());
                    if (pvp > 50000) {
                        tfPVP.setText("50000€");
                    } else {
                        tfPVP.setText(pvp + "€");
                    }
                } catch (Exception e) {
                    tfPVP.setText("");
                }
            }

            @Override
            public void focusGained(FocusEvent arg0) {
            }
        });

        tfTelefono.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();
                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0' || tfTelefono.getText().length() >= 9 )|| (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();
                }
            }
        });
        this.setTitle("Comprar coche");
        @SuppressWarnings("unused")
        Image icon = new ImageIcon("logoHotel.png").getImage();
        this.setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroup = new javax.swing.ButtonGroup();
        panel01 = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        panel02 = new javax.swing.JPanel();
        etCodigo = new javax.swing.JLabel();
        tfCodigo = new javax.swing.JTextField();
        etModelo = new javax.swing.JLabel();
        tfModelo = new javax.swing.JTextField();
        etMarca = new javax.swing.JLabel();
        tfMarca = new javax.swing.JTextField();
        panel03 = new javax.swing.JPanel();
        etFechaAlta = new javax.swing.JLabel();
        SpinnerModel modeloFecha = new SpinnerDateModel();
        sFechaAlta = new javax.swing.JSpinner(modeloFecha);
        etProveedor = new javax.swing.JLabel();
        tfProveedor = new javax.swing.JTextField();
        etTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        etPrecioCoste = new javax.swing.JLabel();
        tfPrecioCoste = new javax.swing.JTextField();
        etUbicacion = new javax.swing.JLabel();
        tfUbicacion = new javax.swing.JTextField();
        etPVP = new javax.swing.JLabel();
        tfPVP = new javax.swing.JTextField();
        etTipoMotor = new javax.swing.JLabel();
        rbGasolina = new javax.swing.JRadioButton();
        rbDiesel = new javax.swing.JRadioButton();
        rbHibrido = new javax.swing.JRadioButton();
        rbElectrico = new javax.swing.JRadioButton();
        etTipoVehiculo = new javax.swing.JLabel();
        cbTipoVehiculo = new javax.swing.JComboBox();
        etTipoCambio = new javax.swing.JLabel();
        cbTipoCambio = new javax.swing.JComboBox();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(144, 219, 222));
        setMaximumSize(new java.awt.Dimension(572, 500));
        setPreferredSize(null);
        setSize(getPreferredSize());

        panel01.setBackground(new java.awt.Color(30, 123, 126));

        etTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        etTitulo.setText("Hotel Antequera");
        etTitulo.setAlignmentX(1.0F);

        javax.swing.GroupLayout panel01Layout = new javax.swing.GroupLayout(panel01);
        panel01.setLayout(panel01Layout);
        panel01Layout.setHorizontalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel01Layout.setVerticalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );

        panel02.setBackground(new java.awt.Color(30, 123, 126));

        etCodigo.setText("Codigo:");

        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        etModelo.setText("Modelo");

        etMarca.setText("Marca");

        javax.swing.GroupLayout panel02Layout = new javax.swing.GroupLayout(panel02);
        panel02.setLayout(panel02Layout);
        panel02Layout.setHorizontalGroup(
            panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(tfMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(panel02Layout.createSequentialGroup()
                        .addGroup(panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel02Layout.setVerticalGroup(
            panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etCodigo)
                .addGap(5, 5, 5)
                .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel03.setBackground(new java.awt.Color(30, 123, 126));

        etFechaAlta.setText("Fecha de Alta");

        etProveedor.setText("Proveedor");

        etTelefono.setText("Teléfono");

        etPrecioCoste.setText("Precio coste");

        etUbicacion.setText("Ubicacion");

        etPVP.setText("PVP");

        etTipoMotor.setText("Tipo Motor");

        rbGasolina.setText("Gasolina");
        rbGasolina.setOpaque(false);

        rbDiesel.setText("Diesel");
        rbDiesel.setOpaque(false);

        rbHibrido.setText("Hibrido");
        rbHibrido.setOpaque(false);

        rbElectrico.setText("Electrico");
        rbElectrico.setOpaque(false);

        etTipoVehiculo.setText("Tipo Vehiculo");

        cbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Turismo", "monovolumen", "SUV", "Todoterreno" }));

        etTipoCambio.setText("Tipo Cambio");

        cbTipoCambio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Automatico" }));

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel03Layout = new javax.swing.GroupLayout(panel03);
        panel03.setLayout(panel03Layout);
        panel03Layout.setHorizontalGroup(
            panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel03Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etFechaAlta)
                        .addComponent(etProveedor)
                        .addComponent(etTelefono)
                        .addComponent(tfTelefono)
                        .addComponent(tfProveedor)
                        .addComponent(sFechaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(bAceptar))
                .addGap(27, 27, 27)
                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPVP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPVP)
                    .addComponent(etUbicacion)
                    .addComponent(etPrecioCoste)
                    .addComponent(tfPrecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelar))
                .addGap(18, 18, 18)
                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel03Layout.createSequentialGroup()
                        .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel03Layout.createSequentialGroup()
                                .addComponent(etTipoMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(rbGasolina)
                            .addComponent(rbDiesel)
                            .addComponent(rbHibrido)
                            .addComponent(rbElectrico))
                        .addGap(26, 26, 26))
                    .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etTipoVehiculo)
                        .addComponent(etTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
        );
        panel03Layout.setVerticalGroup(
            panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel03Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel03Layout.createSequentialGroup()
                        .addComponent(etTipoMotor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbHibrido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbElectrico, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(etTipoVehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel03Layout.createSequentialGroup()
                        .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etPrecioCoste)
                            .addComponent(etFechaAlta))
                        .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel03Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(etUbicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel03Layout.createSequentialGroup()
                                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPrecioCoste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(etProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etTelefono)
                                    .addComponent(etPVP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPVP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(26, 26, 26)
                .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel03Layout.createSequentialGroup()
                        .addComponent(etTipoCambio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bAceptar)
                        .addComponent(bCancelar)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel03, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        tfCodigo.setText("");
        tfMarca.setText("");
        rbGasolina.setSelected(true);
        cbTipoVehiculo.setSelectedIndex(0);

        tfUbicacion.setText("");
        tfModelo.setText("");
        sFechaAlta.setValue(new Date());
        tfProveedor.setText("");
        tfTelefono.setText("");
        tfPrecioCoste.setText("");
        tfPVP.setText("");
        cbTipoCambio.setSelectedIndex(0);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
       tfCodigo.setText("");
        tfMarca.setText("");
        rbGasolina.setSelected(true);
        cbTipoVehiculo.setSelectedIndex(0);

        tfUbicacion.setText("");
        tfModelo.setText("");
        sFechaAlta.setValue(new Date());
        tfProveedor.setText("");
        tfTelefono.setText("");
        tfPrecioCoste.setText("");
        tfPVP.setText("");
        cbTipoCambio.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "Datos guardados correctamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vDialogo dialog = new vDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.ButtonGroup bGroup;
    private javax.swing.JComboBox cbTipoCambio;
    private javax.swing.JComboBox cbTipoVehiculo;
    private javax.swing.JLabel etCodigo;
    private javax.swing.JLabel etFechaAlta;
    private javax.swing.JLabel etMarca;
    private javax.swing.JLabel etModelo;
    private javax.swing.JLabel etPVP;
    private javax.swing.JLabel etPrecioCoste;
    private javax.swing.JLabel etProveedor;
    private javax.swing.JLabel etTelefono;
    private javax.swing.JLabel etTipoCambio;
    private javax.swing.JLabel etTipoMotor;
    private javax.swing.JLabel etTipoVehiculo;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JLabel etUbicacion;
    private javax.swing.JPanel panel01;
    private javax.swing.JPanel panel02;
    private javax.swing.JPanel panel03;
    private javax.swing.JRadioButton rbDiesel;
    private javax.swing.JRadioButton rbElectrico;
    private javax.swing.JRadioButton rbGasolina;
    private javax.swing.JRadioButton rbHibrido;
    private javax.swing.JSpinner sFechaAlta;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfPVP;
    private javax.swing.JTextField tfPrecioCoste;
    private javax.swing.JTextField tfProveedor;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfUbicacion;
    // End of variables declaration//GEN-END:variables
}
