/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author seran
 */
public class Vdialogo extends javax.swing.JDialog {

    /**
     * Creates new form vDialogo
     */
    public Vdialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("CUESTIONARIO DE RESERVA");
    }

    Vdialogo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel01 = new javax.swing.JPanel();
        etTitulo = new javax.swing.JLabel();
        panel02 = new javax.swing.JPanel();
        etNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        etApellidos = new javax.swing.JLabel();
        tfApellidos = new javax.swing.JTextField();
        etDireccion = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        etTelefono = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jPanel03 = new javax.swing.JPanel();
        etFechaEntrada = new javax.swing.JLabel();
        etFechaSalida = new javax.swing.JLabel();
        etNDias = new javax.swing.JLabel();
        tfNDias = new javax.swing.JTextField();
        etTipoHabitacion = new javax.swing.JLabel();
        cbTipoHab = new javax.swing.JComboBox();
        etNHabitaciones = new javax.swing.JLabel();
        sNHabitaciones = new javax.swing.JSpinner();
        etNinios = new javax.swing.JLabel();
        cbNinios = new javax.swing.JCheckBox();
        pNinios = new javax.swing.JPanel();
        etEdad = new javax.swing.JLabel();
        sEdad = new javax.swing.JSpinner();
        tfEdad = new javax.swing.JTextField();
        sEntrada = new javax.swing.JSpinner();
        sSalida = new javax.swing.JSpinner();
        bAceptar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();
        panel04 = new javax.swing.JTabbedPane();
        pPersonales = new javax.swing.JPanel();
        ta01 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        pHabitacion = new javax.swing.JPanel();
        ta02 = new javax.swing.JScrollPane();
        area2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel01.setBackground(new java.awt.Color(30, 123, 126));

        etTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        etTitulo.setText("Hotel Antequera");
        etTitulo.setAlignmentX(1.0F);

        javax.swing.GroupLayout panel01Layout = new javax.swing.GroupLayout(panel01);
        panel01.setLayout(panel01Layout);
        panel01Layout.setHorizontalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel01Layout.setVerticalGroup(
            panel01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel02.setBackground(new java.awt.Color(30, 123, 126));

        etNombre.setText("Nombre:");

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        etApellidos.setText("Apellidos:");

        etDireccion.setText("Direccion:");

        etTelefono.setText("Telefono:");

        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });
        tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTelefonoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel02Layout = new javax.swing.GroupLayout(panel02);
        panel02.setLayout(panel02Layout);
        panel02Layout.setHorizontalGroup(
            panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel02Layout.createSequentialGroup()
                        .addGroup(panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfApellidos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTelefono)
                            .addGroup(panel02Layout.createSequentialGroup()
                                .addGroup(panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(panel02Layout.createSequentialGroup()
                        .addComponent(etTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))))
        );
        panel02Layout.setVerticalGroup(
            panel02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel02Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(etNombre)
                .addGap(3, 3, 3)
                .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etApellidos)
                .addGap(3, 3, 3)
                .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etDireccion)
                .addGap(3, 3, 3)
                .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(etTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        etFechaEntrada.setText("Fecha Entrada:");

        etFechaSalida.setText("Fecha Salida:");

        etNDias.setText("Numero dias:");

        tfNDias.setText("1");

        etTipoHabitacion.setText("Tipo Habitación:");

        cbTipoHab.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Double", "Suite" }));

        etNHabitaciones.setText("N Habitaciones");

        sNHabitaciones.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        etNinios.setText("¿Niños?");

        cbNinios.setOpaque(false);
        cbNinios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cbNiniosStateChanged(evt);
            }
        });

        pNinios.setVisible(false);

        etEdad.setText("Edad");

        sEdad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 14, 1));
        sEdad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sEdadStateChanged(evt);
            }
        });

        tfEdad.setEditable(false);

        javax.swing.GroupLayout pNiniosLayout = new javax.swing.GroupLayout(pNinios);
        pNinios.setLayout(pNiniosLayout);
        pNiniosLayout.setHorizontalGroup(
            pNiniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNiniosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pNiniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pNiniosLayout.createSequentialGroup()
                        .addComponent(etEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNiniosLayout.setVerticalGroup(
            pNiniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNiniosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pNiniosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etEdad)
                    .addComponent(sEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sEntrada.setModel(new javax.swing.SpinnerDateModel());

        sSalida.setModel(new javax.swing.SpinnerDateModel());

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        bImprimir.setText("Imprimir");
        bImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel03Layout = new javax.swing.GroupLayout(jPanel03);
        jPanel03.setLayout(jPanel03Layout);
        jPanel03Layout.setHorizontalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etFechaEntrada)
                            .addComponent(etFechaSalida))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel03Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(sSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel03Layout.createSequentialGroup()
                                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etNinios)
                                    .addGroup(jPanel03Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(cbNinios)))
                                .addGap(37, 37, 37)
                                .addComponent(pNinios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel03Layout.createSequentialGroup()
                                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel03Layout.createSequentialGroup()
                                        .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(etTipoHabitacion)
                                            .addComponent(etNDias))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNDias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel03Layout.createSequentialGroup()
                                        .addComponent(etNHabitaciones)
                                        .addGap(12, 12, 12)
                                        .addComponent(sNHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar)
                        .addGap(39, 39, 39))))
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(bImprimir)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel03Layout.setVerticalGroup(
            jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel03Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFechaEntrada)
                    .addComponent(sEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etFechaSalida)
                    .addComponent(sSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNDias)
                    .addComponent(tfNDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etTipoHabitacion)
                    .addComponent(cbTipoHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etNHabitaciones)
                    .addComponent(sNHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel03Layout.createSequentialGroup()
                        .addComponent(etNinios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbNinios))
                    .addComponent(pNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCancelar)
                    .addComponent(bAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bImprimir)
                .addGap(7, 7, 7))
        );

        area1.setColumns(20);
        area1.setRows(5);
        ta01.setViewportView(area1);

        javax.swing.GroupLayout pPersonalesLayout = new javax.swing.GroupLayout(pPersonales);
        pPersonales.setLayout(pPersonalesLayout);
        pPersonalesLayout.setHorizontalGroup(
            pPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ta01, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        pPersonalesLayout.setVerticalGroup(
            pPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersonalesLayout.createSequentialGroup()
                .addComponent(ta01, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel04.addTab("tab1", pPersonales);

        area2.setColumns(20);
        area2.setRows(5);
        ta02.setViewportView(area2);

        javax.swing.GroupLayout pHabitacionLayout = new javax.swing.GroupLayout(pHabitacion);
        pHabitacion.setLayout(pHabitacionLayout);
        pHabitacionLayout.setHorizontalGroup(
            pHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHabitacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ta02, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        pHabitacionLayout.setVerticalGroup(
            pHabitacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHabitacionLayout.createSequentialGroup()
                .addComponent(ta02, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel04.addTab("tab2", pHabitacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel04, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel03, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(panel04, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panel01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoActionPerformed

    private void tfTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTelefonoKeyTyped
        char num = evt.getKeyChar();
        if(num > '9' || num < '0') evt.consume();
    }//GEN-LAST:event_tfTelefonoKeyTyped

    private void cbNiniosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cbNiniosStateChanged
        if(cbNinios.isSelected()){
            pNinios.setVisible(true);
        } else {
            pNinios.setVisible(false);
        }
    }//GEN-LAST:event_cbNiniosStateChanged

    private void sEdadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sEdadStateChanged
        int edad = Integer.parseInt(sEdad.getValue().toString());
        if(edad < 5){
            tfEdad.setText("Cuna");
        } else {
            if(edad < 11) {
                tfEdad.setText("Cama pequeña");
            } else {
                if (edad < 15){
                    tfEdad.setText("Cama normal");
                }
            }
        }
        
    }//GEN-LAST:event_sEdadStateChanged

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        tfNombre.setText("");
        tfApellidos.setText("");
        tfDireccion.setText("");
        tfTelefono.setText("");
        tfNDias.setText("1");
        tfEdad.setText("");
        pNinios.setVisible(false);
        sEntrada.setValue(new Date());
        sSalida.setValue(new Date());
        sEdad.setValue(0);
        sNHabitaciones.setValue(0);
         
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        tfNombre.setText("");
        tfApellidos.setText("");
        tfDireccion.setText("");
        tfTelefono.setText("");
        tfNDias.setText("1");
        tfEdad.setText("");
        pNinios.setVisible(false);
        sEntrada.setValue(new Date());
        sSalida.setValue(new Date());
        sEdad.setValue(0);
        sNHabitaciones.setValue(0);
        JOptionPane.showMessageDialog(this, "Todo guardado correctamente");
    }//GEN-LAST:event_bAceptarActionPerformed

    private void bImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirActionPerformed
        String cadena1, cadena2;
		cadena1 = "Nombre: " + tfNombre.getText() +
				"\nApellido: " + tfApellidos.getText() +
				"\nDirección: " + tfDireccion.getText() +
				"\nTeléfono: " + tfTelefono.getText();
		area1.setText(cadena1);
		
		String aux = "";
		if (cbTipoHab.getSelectedIndex() == 0) {
			aux = "Simple";
		}
		if (cbTipoHab.getSelectedIndex() == 1) {
			aux = "Doble";
		}
		if (cbTipoHab.getSelectedIndex() == 2) {
			aux = "Suit";
		}
		
		
		cadena2 = "Fecha entrada: " + sEntrada.getValue().toString() + 
				"\nFecha salida: " + sSalida.getValue().toString() + 
				"\nNumero dias: " + tfNDias.getText() + 
				"\nOpcion tipo habitacion: " + aux + 
				"\nNumero habitaciones: " + sNHabitaciones.getValue().toString();
		area2.setText(cadena2);
    }//GEN-LAST:event_bImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vdialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vdialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vdialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vdialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vdialogo dialog = new Vdialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JTextArea area2;
    private javax.swing.JButton bAceptar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JCheckBox cbNinios;
    private javax.swing.JComboBox cbTipoHab;
    private javax.swing.JLabel etApellidos;
    private javax.swing.JLabel etDireccion;
    private javax.swing.JLabel etEdad;
    private javax.swing.JLabel etFechaEntrada;
    private javax.swing.JLabel etFechaSalida;
    private javax.swing.JLabel etNDias;
    private javax.swing.JLabel etNHabitaciones;
    private javax.swing.JLabel etNinios;
    private javax.swing.JLabel etNombre;
    private javax.swing.JLabel etTelefono;
    private javax.swing.JLabel etTipoHabitacion;
    private javax.swing.JLabel etTitulo;
    private javax.swing.JPanel jPanel03;
    private javax.swing.JPanel pHabitacion;
    private javax.swing.JPanel pNinios;
    private javax.swing.JPanel pPersonales;
    private javax.swing.JPanel panel01;
    private javax.swing.JPanel panel02;
    private javax.swing.JTabbedPane panel04;
    private javax.swing.JSpinner sEdad;
    private javax.swing.JSpinner sEntrada;
    private javax.swing.JSpinner sNHabitaciones;
    private javax.swing.JSpinner sSalida;
    private javax.swing.JScrollPane ta01;
    private javax.swing.JScrollPane ta02;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfNDias;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
