/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientegrafico;

import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Angel Salas Calvo
 */
public class VentanaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCliente
     */
    public VentanaCliente() {
        initComponents();
        cliente = new Cliente(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jTFMensaje = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jBConectar = new javax.swing.JButton();
        jLPuerto = new javax.swing.JLabel();
        jLServidor = new javax.swing.JLabel();
        jBSalir = new javax.swing.JButton();
        jLConectado = new javax.swing.JLabel();
        jLConectadoIndicar = new javax.swing.JLabel();
        jTFServidor = new javax.swing.JTextField();
        jTFPuerto = new javax.swing.JTextField();
        jSPConversacion = new javax.swing.JScrollPane();
        jTAConversacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("CLIENTE GRÁFICO");

        jTFMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFMensajeKeyPressed(evt);
            }
        });

        jBEnviar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBEnviar.setText("ENVIAR");
        jBEnviar.setEnabled(false);
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jPanelDatos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatos.setOpaque(false);

        jBConectar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBConectar.setText("CONECTAR");
        jBConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConectarActionPerformed(evt);
            }
        });

        jLPuerto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLPuerto.setText("Puerto");

        jLServidor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLServidor.setText("Servidor");

        jBSalir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jLConectado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLConectado.setText("Conectado");

        jLConectadoIndicar.setBackground(new java.awt.Color(255, 51, 51));
        jLConectadoIndicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/off.png"))); // NOI18N

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLConectado, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jTFPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTFServidor)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLConectadoIndicar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFServidor)
                    .addComponent(jLServidor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLConectadoIndicar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTAConversacion.setColumns(20);
        jTAConversacion.setRows(5);
        jTAConversacion.setFocusable(false);
        jTAConversacion.setEditable(false);
        jSPConversacion.setViewportView(jTAConversacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFMensaje)
                    .addComponent(jSPConversacion, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSPConversacion, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //--------------------------------------------------------------------------
    
    /**
     * METODO PARA SALIR DE LA APLICACIÓN
     * @param evt 
     */
    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        cliente.cerrarConexion();
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    //--------------------------------------------------------------------------
    
    /**
     * METODO QUE SE EJECUTA AL HACER CLIC EN EL BOTON CONECTAR
     * Comprueba que los datos de conexión tienen un formato adecuado
     * @param evt 
     */
    private void jBConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConectarActionPerformed
        //Comprobar que se ha introducido datos en los 2 campos necesarios
        if(jTFPuerto.getText().isEmpty()==false && jTFServidor.getText().isEmpty()==false){
            String ipTexto = jTFServidor.getText().trim();
            int puerto = 0;
            InetAddress ip = null;

            //Dar valor a las variables si los datos introducidos son correctos
            try {
                puerto = Integer.parseInt(jTFPuerto.getText());
                ip = InetAddress.getByName(ipTexto);
            } catch (UnknownHostException ex) {
                //Si no se puede crear la ip con el texto introducido, se notificará
                JOptionPane.showMessageDialog(this, "Formato de dirección IP introducida erroneo.","", JOptionPane.ERROR_MESSAGE);
            }catch (NumberFormatException ne){
                //Si no se puede crear la ip con el texto introducido, se notificará
                JOptionPane.showMessageDialog(this, "Puerto de conexión introducido erroneo.","", JOptionPane.ERROR_MESSAGE);
            }

            //Si los datos introducidos son correctos abrimos la conexión del cliente
            if(puerto!=0 && ip!=null){
                //Si se ha podido establecer la conexión realizadamos las acciones correspondientes
                if(cliente.abrirConexion(ip, puerto)){
                    jBEnviar.setEnabled(true);
                    jBConectar.setEnabled(false);
                    //Cambiar el icono de conexion
                    jLConectadoIndicar.setIcon(new ImageIcon(getClass().getResource("/img/on.png")));
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe especificar una dirección IP y puerto para establecer la conexión.","", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBConectarActionPerformed

    //--------------------------------------------------------------------------
    
    /**
     * METODO PARA ENVIAR MENSAJE AL SERVIDOR
     * @param evt 
     */
    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        String mensaje = jTFMensaje.getText();
        cliente.enviarMensaje(mensaje);
        jTFMensaje.setText(""); //limpiar el campo
        jTAConversacion.append("\nCLIENTE: "+mensaje);
    }//GEN-LAST:event_jBEnviarActionPerformed

    //--------------------------------------------------------------------------
    
    /**
     * METODO PARA ENVIAR MENSAJE AL PULSAR LA TECLA ENTER
     * @param evt 
     */
    private void jTFMensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMensajeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            jBEnviar.doClick();
    }//GEN-LAST:event_jTFMensajeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConectar;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLConectado;
    private javax.swing.JLabel jLConectadoIndicar;
    private javax.swing.JLabel jLPuerto;
    private javax.swing.JLabel jLServidor;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JScrollPane jSPConversacion;
    public static javax.swing.JTextArea jTAConversacion;
    private javax.swing.JTextField jTFMensaje;
    private javax.swing.JTextField jTFPuerto;
    private javax.swing.JTextField jTFServidor;
    // End of variables declaration//GEN-END:variables
    private Cliente cliente;
}