/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ej1_1;

import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author windiurno
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form main
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbComidas = new javax.swing.JComboBox();
        tfTexto = new javax.swing.JTextField();

        cbComidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pollo", "Pescado", "Sopa" }));
        cbComidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbComidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cbComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbComidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbComidasActionPerformed
        if(cbComidas.getSelectedIndex() == 0){
            tfTexto.setText("Pollo con patatas");
        }
        if(cbComidas.getSelectedIndex() == 1){
            tfTexto.setText("Pescado con patatas");
        }
        if(cbComidas.getSelectedIndex() == 2){
            tfTexto.setText("Sopa con patatas");
        }
    }//GEN-LAST:event_cbComidasActionPerformed

    public JComboBox getCbComidas() {
        return cbComidas;
    }

    public void setCbComidas(JComboBox cbComidas) {
        this.cbComidas = cbComidas;
    }

    public JTextField getTfTexto() {
        return tfTexto;
    }

    public void setTfTexto(JTextField tfTexto) {
        this.tfTexto = tfTexto;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbComidas;
    private javax.swing.JTextField tfTexto;
    // End of variables declaration//GEN-END:variables
}
