
package vista;
import java.awt.Color;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VistaConectar extends javax.swing.JFrame {
    
    InetAddress direccionIP;
    int puerto;
    Socket conexion;
    
    VistaChat vChat;
    
    public VistaConectar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(63, 150, 172));
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaConectar().setVisible(true);
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDireccionIP = new javax.swing.JTextField();
        tfPuerto = new javax.swing.JTextField();
        bConectar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");
        setBackground(new java.awt.Color(51, 153, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dirección IP:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 54, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Puerto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 111, -1, -1));

        tfDireccionIP.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tfDireccionIP.setText("localhost");
        getContentPane().add(tfDireccionIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 50, 146, -1));

        tfPuerto.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tfPuerto.setText("15000");
        tfPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPuertoActionPerformed(evt);
            }
        });
        getContentPane().add(tfPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 107, 146, -1));

        bConectar.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        bConectar.setText("Conectar");
        bConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 157, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/131306.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 330, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPuertoActionPerformed

    private void bConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConectarActionPerformed
        
        String ipCad = tfDireccionIP.getText();
        String puertoCad = tfPuerto.getText();

        //--------------------------------------------------------------
        //Convertimos los datos
        try {
            direccionIP = InetAddress.getByName(ipCad);
            puerto = Integer.parseInt(puertoCad);
            
            conexion = new Socket(direccionIP, puerto);
            
            
            this.setVisible(false);
            vChat = new VistaChat(conexion);
            vChat.setVisible(true);

        } catch (UnknownHostException ex) {
            System.err.println("Formato de Dirreción IP Errorneo o Desconocido");
            System.exit(-1);
        } catch (NumberFormatException ex) {
            System.err.println("Formato Puerto Erroneo!!!!");
            System.exit(-1);
        } catch (IOException ex) {
            Logger.getLogger(VistaConectar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Imposible conectar al servidor");
        }
    }//GEN-LAST:event_bConectarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bConectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JTextField tfDireccionIP;
    public javax.swing.JTextField tfPuerto;
    // End of variables declaration//GEN-END:variables

}
